graph TD
	db[(Database)]
	dbh([Datebase Handler])
	dbcache([Database Caching Server])
	web([Website])
	jwt[JWT Authentication Server]
	leviathan[Leviathan]
	api[Leviathan API]
	cronmanager[Cron Manager]
	cronjob[[Cron Job]]
	appmanager[App Manager]
	app[[Application]]

	web-->dbcache
	web-.->|requires JWT token|leviathan
	web-->|has login route|jwt
	leviathan-.-|verifies token|jwt
	leviathan-.->|implements|api
	jwt-->dbcache
	api-.-|can manage|cronmanager
	api-.-|can manage|appmanager
	cronmanager-->dbcache
	cronmanager-->cronjob
	cronjob-->dbcache
	appmanager-->dbcache
	appmanager-->app
	app-->dbcache
	dbcache-->dbh
	dbh-->db