graph TD
	subgraph data [Data]
	db[(Database)]
	session[(Session)]
	dbh([Datebase Handler])
	end

	subgraph ui [UI]
	web([Website])
	leviathan[Leviathan]
	end

	subgraph system [System]
	jwt[JWT Authentication Server]
	api[Leviathan API]
	cronmanager[Cron Manager]
	cronjob[[Cron Job]]
	appmanager[App Manager]
	app[[Application]]
	end

	web-->dbh
	web-.->|requires JWT token|leviathan
	web-->|has login route|jwt
	leviathan-.-|verifies token|jwt
	leviathan-.->|implements|api
	jwt-->dbh
	api-.-|can manage|cronmanager
	api-.-|can manage|appmanager
	cronmanager-->dbh
	cronmanager-->cronjob
	cronjob-->dbh
	appmanager-->dbh
	appmanager-->app
	app-->dbh
	leviathan---->session
	web-->session
	dbh-->db