graph TD
	db[(Database)]
	dbh([Datebase Handler])
	web([Website])
	jwt[JWT Authentication Server]
	leviathan[Leviathan]
	api[Leviathan API]
	cronmanager[Cron Manager]
	cronjob[[Cron Job]]
	appmanager[App Manager]
	app[[Application]]

	web-->dbh
	web-.->|requires JWT token|leviathan
	web-->|has login route|jwt
	leviathan-.-|verifies token|jwt
	leviathan-.->|implements|api
	jwt-->dbh
	api-.-|can manage|cronmanager
	api-.-|can manage|appmanager
	cronmanager-->dbh
	cronmanager-->cronjob
	cronjob-->dbh
	appmanager-->dbh
	appmanager-->app
	app-->dbh
	dbh-->db