version: '3.0'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  session:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - ./data/session:/data