# docker-compose -f database.yaml -p leviathan up
version: '3.0'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    container_name: database
  session:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - ./data/session:/data
    container_name: session